### ISSUE TITLE
Allow commands to be issued by PM

### ISSUE THREAD

**Issue by qaisjp** [chillroom/jacr-bot#2]
This issue depends on https://github.com/anjanms/DubAPI/issues/14

**Comment by Purnceks** [comment]
What's a PM in this context

**Comment by qaisjp** [comment]
private message

**Comment by Purnceks** [comment]
So that you can anonymously use commands? When would that serve a purpose?

**Comment by qaisjp** [comment]
prevents spam. mods can issue several config based commands

**Comment by Purnceks** [comment]
Using a command isn't spam? Sorry, I just don't see the point in this one unless you want animosity

**Comment by qaisjp** [comment]
commands like setting the message of the day, or doing private admin commands may need anonymity

anything that shouldn't be kept anonymous (such as who banned who) would be announced in the channel anyway ("Bobby was banned by Tails")

**Comment by qaisjp** [comment]
Closing in favour of web based admin panel
