### ISSUE TITLE
Event mode

### ISSUE THREAD

**Issue by qaisjp** [chillroom/jacr-bot#3]
Add `!event @user`:
1. lock the queue
2. store the queue order 
3. remove the existing dj's
4. add the targeted user to the queue
5. send a message to all users `The event is about to start! Give a warm Chillroom welcome to @{targeteduser}. The queue is now locked, queue positions have been recorded and you will be placed back in your spot when the event ends. Enjoy!`

Add `!event stop`:
1. unlock the queue
2. read the queue order and restore positions to logged in users
3. send a message to everyone `The event is now over, thanks for coming and we hope you all enjoyed it! Check our facebook (https://fb.me/justachillroom) for more information on upcoming events. The DJ queue is now unlocked!`

Things that need checking when adding this feature:
1. Automatic song skipping (see issue #26)

**Comment by Purnceks** [comment]
Send message to all users? You just mean send to chat, or @everyone?
